services:
  xray:
    image: necko1/xray:latest
    container_name: necko-xray
    restart: unless-stopped
    network_mode: "host"
    env_file: .env
    volumes:
      - ./profiles/:/etc/xray/profiles/:rw
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine3.22
    container_name: necko-postgres
    restart: always
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  valkey:
    image: valkey/valkey:9-alpine3.22
    container_name: necko-valkey
    restart: always
    command: valkey-server --requirepass "${VALKEY_PASSWORD}"
    volumes:
      - valkey:/data
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: [ "CMD", "valkey-cli", "-a", "${VALKEY_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres:
  valkey:
